### ISSUE TITLE
Segmentation fault upon running laravel new command

### ISSUE THREAD

**Issue by trevorllarson** [laravel/installer#113]
- Installer Version: 3.0.1

### Description:
Running the command `laravel new sitename`, I am suddenly receiving a segmentation fault error. Running the composer based command, `composer create-project laravel/laravel blog` works as expected.

### Steps To Reproduce:
1. Run `laravel new sitename`
2. Receive "segmentation fault" error

![seg-fault-laravel-new](https://user-images.githubusercontent.com/13206006/77832125-b4c5f680-7101-11ea-8fe6-7e11a3518e30.png)

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. Segmentation faults are bugs in PHP itself, and are not related to this repo. Please isolate the problem and submit a bug report to PHP, assuming your PHP version is the latest version of 7.2, 7.3 or 7.4. Otherwise, upgrade to the latest version in that series, and try again.

**Comment by trevorllarson** [comment]
I was actually able to solve this with a reinstall of php! Apologies for not trying that first, and thanks for the point in the right direction!
