### ISSUE TITLE
Can't use Laravel Installer with Laravel Homestead anymore

### ISSUE THREAD

**Issue by codegefluester** [laravel/installer#164]
- Installer Version: 4.0.5

### Description:
When trying to create a new project in a directory mapped into a Laravel Homestead machine the following error is shown when attempting to create a Laravel project in said directory using the `--force` flag

```
vagrant@homestead:~$ laravel new --force packages

 _                               _
| |                             | |
| |     __ _ _ __ __ ___   _____| |
| |    / _` | '__/ _` \ \ / / _ \ |
| |___| (_| | | | (_| |\ V /  __/ |
|______\__,_|_|  \__,_| \_/ \___|_|

rm: cannot remove '/home/vagrant/packages': Device or resource busy
```

Using `composer create-project` directly works just fine with the existing directory since I am not using the `--remove-vcs` option which I guess is the actual root cause here.

### Steps To Reproduce:
1. Setup a new Laravel Homestead machine following the instructions on https://laravel.com/docs/8.x/homestead
2. Map a folder on the host (in my case macOS 10.15.7) machine to a folder in the Homestead machine
3. Provision, boot and ssh into the machine
4. Install the Laravel installer (in this case v4.0.5)
5. Run `laravel new <name-of-mapped-directory> --force`

This used to work just fine in previous versions of the installer as it was my standard flow to setup a new project in a separate folder in a Homestead machine. As I noted above, using `composer create-project` directly is a workaround.

Edit: I'd also like to note that I acknowledge that this is just a specific issue of how mapped folders work with a VirtualBox machine and that this issue may not be addressed as a result of this

**Comment by driesvints** [comment]
It's not recommended to run the installer in Homestead.

**Comment by codegefluester** [comment]
Fair enough

**Comment by haydenbech** [comment]
Why is Laravel Installer included in Homestead if you don't recommend using it? I've spent an hour now trying to find a way around this issue. The Installer is completely unusable inside Homestead due to the way Homestead's folders are designed to work, but it's still included by default. 

As both of these are first-party packages, I think it makes sense to either fix the issue or remove the installer rather than including it without fixing this issue. 

Is there a workaround that we can use, please?
